server:
  port: 8000

spring:
  application:
    name: service-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix: /dishprovider
  routes:
    service-table:
      path: /tableops/**
    service-order:
      path: /orderops/**
