eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://hereprovides.com:8761/eureka/
server:
  #当前服务端口号
  port: 8780
spring:
  application:
    #当前应用名称
    name: app-owner
  rabbitmq:
    host: hereprovides.com
    port: 5672
    username: admin
    password: admin
