eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://localhost:8761/eureka/
server:
  #当前服务端口号
  port: 8765
spring:
  application:
    #当前应用名称
    name: service-order
  rabbitmq:
    host: hereprovides.com
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: mqTableMessage
          contentType: text/plain